# Generated by Django 4.1 on 2022-09-19 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_date', models.DateField()),
                ('contact_timeslot', models.CharField(choices=[('S1', '9am to 10am'), ('S2', '10am to 11am'), ('S3', '11am to 12pm'), ('S4', '12pm to 1pm'), ('S5', '1pm to 2pm'), ('S6', '2pm to 3pm'), ('S7', '3pm to 4pm'), ('S8', '4pm to 5pm'), ('S9', '5pm to 6pm')], default='S1', max_length=2, unique_for_date='contact_date')),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_date_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contact_date', '-contact_timeslot', 'created_by__username'],
            },
        ),
    ]
