# Generated by Django 4.1 on 2022-09-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactrequests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='email',
        ),
    ]
