# Generated by Django 4.1 on 2022-09-22 01:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactrequests', '0002_remove_contactrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='contact_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='contact_timeslot',
            field=models.CharField(choices=[('S1', '9am to 10am'), ('S2', '10am to 11am'), ('S3', '11am to 12pm'), ('S4', '12pm to 1pm'), ('S5', '1pm to 2pm'), ('S6', '2pm to 3pm'), ('S7', '3pm to 4pm'), ('S8', '4pm to 5pm'), ('S9', '5pm to 6pm')], default='S1', error_messages={'unique_for_date': 'Sorry                                             but this time slot is already                                             booked. Please try another                                             day or another time slot.'}, max_length=2, unique_for_date='contact_date'),
        ),
    ]
