# Generated by Django 4.1 on 2022-09-22 22:17

import contactrequests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactrequests', '0003_alter_contactrequest_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='contact_date',
            field=models.DateField(validators=[contactrequests.models.ContactRequest.future_date]),
        ),
    ]
