# Generated by Django 4.1 on 2022-09-18 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_update_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
