# Generated by Django 4.1 on 2022-09-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_last_update_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_update_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
